image: alpine/edge
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
sources:
  - git+ssh://git@git.sr.ht/~timharek/dotfiles
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - setup: |
      echo 'cd dotfiles' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:timharek/dotfiles.git
      git push --force --mirror git@codeberg.org:timharek/dotfiles.git

