#!/usr/bin/env sh

# Initialize yabai
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Follow mouse
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

# Window
## New window spawn on the left side
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on

## Border (currently disabled)
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff002d47
yabai -m config normal_window_border_color   0xff212121
yabai -m config insert_feedback_color        0xffd75f5f

## Split the amount of the previous window
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

## Mouse actions
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

## Paddings
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

## Space labels
yabai -m space 1 --label web
yabai -m space 2 --label work
yabai -m space 4 --label comms
yabai -m space 5 --label terminal

# Space settings
yabai -m config layout                       bsp

# Window rules
yabai -m rule --add app="^Firefox$"             space=web
yabai -m rule --add app="^Chrome$"              space=work

yabai -m rule --add app="^Systeminnstillinger$" manage=off 
yabai -m rule --add app="^Pika$"                manage=off sticky=on layer=above 
yabai -m rule --add app="^Alfred Preferences$"  manage=off 
yabai -m rule --add app="^Mullvad VPN$"         manage=off border=off
yabai -m rule --add app="^Installerer$"         manage=off sticky=on
yabai -m rule --add app="^TeamViewer$"          manage=off
yabai -m rule --add app="^Numi$"                manage=off sticky=on
yabai -m rule --add app="^Harvest$"             manage=off
yabai -m rule --add app="^LibreOffice$"         manage=off
yabai -m rule --add app="^Bilde i bilde$"       manage=off
yabai -m rule --add app="^Dato$"                manage=off
yabai -m rule --add app="^LuLu$"                manage=off sticky=on layer=above 

echo "yabai configuration loaded.."
