#!/bin/bash

# Author: Tim Hårek Andreassen
# Created: 2021-04-24
# ===============================
# Backs up macOS-system using rsync

ICLOUD_PATH="/Users/$USER/Library/Mobile Documents/com~apple~CloudDocs"

SOURCE_DIR=(~/Documents/ ~/work/ ~/Pictures/)
NUC_DIR=(nuc:Documents/ nuc:Work/ nuc:Pictures/)
ICLOUD_DIR=($ICLOUD_PATH/Dokumenter/ $ICLOUD_PATH/Arbeid/ $ICLOUD_PATH/Bilder/)

display_help() {
    echo "Backs up macOS-system using rsync"
    echo 
    echo "USAGE:"
    echo "  backup"
    echo
    echo "ARGUMENTS:"
    echo "  -h, --help      Print Help (this message)"
    echo "  -d, --dry-run   Dry-run, doesn't actually do any harm"
    echo
    echo "DESCRIPTION:"
    echo "  Backs up macOS-system with rsync to:"
    echo "      nuc"
    echo "      iCloud"
    echo "  From:"
    for dir in "${SOURCE_DIR[@]}"
    do
        echo "      $dir"
    done
    echo

    exit 0
}


archive() {
    rsync -avhz --delete \
        --exclude '.DS_Store' \
        --exclude '$RECYCLE.BIN' \
        --exclude 'Photo Booth-biblitotek' \
        --exclude 'Photos Library.photoslibrary' \
        $1 $2
}

backup() {
    if [ "${#SOURCE_DIR[@]}" != "${#NUC_DIR[@]}" ]; then
        echo "The amount of directories does not match"
        exit 0
    fi

    for i in "${!SOURCE_DIR[@]}"
    do
        archive "${SOURCE_DIR[i]}" "${NUC_DIR[i]}"
        archive "${SOURCE_DIR[i]}" "${ICLOUD_DIR[i]}"
        echo "Backed up ${SOURCE_DIR[i]} successfully!"
    done
}

backup-dry() {
    if [ "${#SOURCE_DIR[@]}" != "${#NUC_DIR[@]}" ]; then
        echo "The amount of directories does not match"
        exit 0
    fi

    for i in "${!SOURCE_DIR[@]}"
    do
        archive --dry-run "${SOURCE_DIR[i]}" "${NUC_DIR[i]}"
        archive --dry-run "${SOURCE_DIR[i]}" "${ICLOUD_DIR[i]}"
        echo "Backed up ${SOURCE_DIR[i]} successfully!"
    done
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    display_help
elif [ "$1" == "-d" ] || [ "$1" == "--dry-run" ]; then
    backup-dry
else
    backup
fi
