#!/bin/sh

notePath="$HOME/Notater"
noteFilename="$notePath/note-$(date +%Y-%m-%d).md"

if [ ! -f $noteFilename ]; then
    echo "# Notes for $(date +%Y-%m-%d)" > $noteFilename
fi

cd $notePath

$EDITOR $noteFilename