#!/bin/bash

workStart() {
  echo "Launching all applications."
  open -a "Slack"
  open -a "Google Chrome" --args --profile-directory=Default
  open -a "Harvest"
}

workEnd() {
  echo "Closing all applications."
  osascript -e 'quit app "Slack"'
  osascript -e 'quit app "Google Chrome"'
  osascript -e 'quit app "Harvest"'
}

displayHelp() {
  echo "Work"
  echo 
  echo "USAGE:"
  echo "  work"
  echo
  echo "ARGUMENTS:"
  echo "  -h  Print Help (this message)"
  echo "  -s  Launch all work applications"
  echo "  -e  Quit all work applications"
  echo
  echo "DESCRIPTION:"
  echo "  For being lazy, launching and quiting all work related applications."
  echo

  exit 0
}


if [[ $# -eq 0 ]]; then
    displayHelp
    exit
fi

while getopts 'seh' flag; do
  case "${flag}" in
    s)  workStart
      ;;
    e)  workEnd
      ;;
    h | *)
        displayHelp
        exit 1
      ;;
  esac
done

