#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
#yabai -m config window_border                on
#yabai -m config window_border_width          2
#yabai -m config active_window_border_color   0xff00a2fd
#yabai -m config normal_window_border_color   0xff212121
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config window_gap                   06

yabai -m space 1 --label web
yabai -m space 2 --label mail
yabai -m space 3 --label social

# window rules
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Signal$" space=social

yabai -m rule --add app="^Systemvalg$" manage=off 
yabai -m rule --add app="^Spotify$" manage=off layer=normal
yabai -m rule --add app="^Pika$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off 
yabai -m rule --add app="^Mullvad VPN$" manage=off border=off
yabai -m rule --add app="^Installerer$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Mail$" manage=off

echo "yabai configuration loaded.."
