theme = "onedark"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
rulers = [80]

idle-timeout = 200
completion-trigger-len = 1

end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-x = ":buffer-close"
X = ["extend_line_up", "extend_to_line_bounds"]
C-n = ":new"
C-r = ":reload-all"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["workspace-diagnostics"]
right = ["diagnostics", "version-control" , "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
                   
