theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
rulers = [80]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-x = ":buffer-close"
X = "extend_line_above"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "version-control" , "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.file-picker]
hidden = false
