[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
formatter = { command = "prettierd", args = ["*.md"] }
auto-format = true

[[language]]
name = "html"
auto-format = false

[language-server.deno]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }

[language-server.deno.config.deno]
enable = true
suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }

[[language]]
name = "javascript"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "javascript"
file-types = ["js", "mjs", "cjs", "rules", "es6", "pac", "jakefile"]
shebangs = ["node"]
comment-token = "//"
roots = ["package.json", "tsconfig.json"]
language-servers = [ "typescript-language-server" ]

[[language]]
name = "jsx"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "jsx"
scope = "source.jsx"
file-types = ["jsx"]
comment-token = "//"
roots = ["package.json", "tsconfig.json"]
language-servers = [ "typescript-language-server" ]

[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts", "mts", "cts"]
shebangs = ["deno", "ts-node"]
roots = ["package.json", "tsconfig.json"]
language-servers = [ "typescript-language-server" ]

[[language]]
name = "tsx"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
file-types = ["tsx"]
comment-token = "//"
roots = ["package.json", "tsconfig.json"]
language-servers = [ "typescript-language-server" ]
