[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
formatter = { command = "prettierd", args = ["*.md"] }
auto-format = true

[[language]]
name = "html"
auto-format = false

[language-server.deno]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }

[language-server.deno.config.deno]
enable = true
suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }

[[language]]
name = "javascript"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "jsx"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "tsx"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[language-server.efm-lsp-prettier]
command = "efm-langserver"

[language-server.efm-lsp-prettier.config]
documentFormatting = true
languages = { typescript = [ { formatCommand ="prettier --stdin-filepath ${INPUT}", formatStdin = true } ] }

[[language]]
name = "prisma"
auto-format = true

