[language-server.deno]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }

[language-server.deno.config.deno]
enable = true
suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }

[language-server.emmet]
command = "emmet-ls"
args = [ "--stdio" ]

[language-server.efm-lsp-prettier]
command = "efm-langserver"

[language-server.efm-lsp-prettier.config]
documentFormatting = true
languages = { typescript = [ { formatCommand ="prettier --stdin-filepath ${INPUT}", formatStdin = true } ] }

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
formatter = { command = "prettierd", args = ["*.md"] }
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "ansible-language-server"]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "javascript"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "jsx"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno", "emmet"]
auto-format = true

[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno"]
auto-format = true

[[language]]
name = "tsx"
shebangs = ["deno"]
roots = ["deno.json"]
language-servers = ["deno", "emmet"]
auto-format = true

[[language]]
name = "prisma"
auto-format = true

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet" ]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "scss"
language-servers = [ "vscode-css-language-server", "emmet" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
file-types = ["scss"]
auto-format = true

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.pkl-ls]
command = "/Users/tim/tmp/pkl-lsp/bin/pkl-lsp"

[[language]]
name = "pkl"
language-servers = [ "pkl-ls" ]
